####### OWNER ENDPOINTS

### All Owners
GET http://localhost:8000/api/owners   
# successfully retrieves owners list

### Test Single Authors
GET http://localhost:8000/api/owners/12
# successfully retrieves single owner

### Test POST Request for new Owner
POST http://localhost:8000/api/owners/
Content-Type: application/json

{
  "name": "Jonathan Grieve",
  "copyright": "JGDM Photography",
  "year": "2020"
}


### Test POST Request for editing a record
POST http://localhost:8000/api/owners/12?_method=PUT
Content-Type: application/json

{
  "name": "Jonnie Grieve",
  "copyright": "JG Photography",
  "year": "2020"
}


### DELETE a specific record 

DELETE http://localhost:8000/api/owners/11



####### PHOTO ENDPOINTS

### All Photos
GET http://localhost:8000/api/photos   
# successfully retrieves photos list

### Test Photos Authors
GET http://localhost:8000/api/photos/9/
# successfully retrieves single photo

### Test POST Request for adding new Photo Record
POST http://localhost:8000/api/photos/
Content-Type: application/json

{
  "url": "img/photo.png",
  "caption": "photo of a cat",
  "owner_id": "11"
}


### Test POST Request for editing a record
POST http://localhost:8000/api/photos/11?_method=PUT
Content-Type: application/json

{
  "url": "img/photos.png",
  "captions": "new cat photo",
  "owner_id": "4"
}

### Delete Photo Resource
DELETE http://localhost:8000/api/photos/10

